console.log('action type')
// export const GET_AUTH_USER_LOGIN_REQUEST = 'GET_AUTH_USER_LOGIN_REQUEST'
// export const GET_AUTH_USER_LOGIN_SUCCESS = 'GET_AUTH_USER_LOGIN_SUCCESS'
// export const GET_AUTH_USER_LOGIN_FAILURE = 'GET_AUTH_USER_LOGIN_FAILURE'

export const GET_REQUEST = 'GET_REQUEST'
export const GET_SUCCESS = 'GET_SUCCESS'
export const GET_FAILURE = 'GET_FAILURE'

